image: node:lts

cache:
  paths:
  - node_modules/

stages:
  - build-documentation

pages:
  stage: build-documentation
  script:
   - npm rebuild
   - npm install
   - npm run build-documentation
  artifacts:
    paths:
      - public
  tags:
   - docker
